# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            "满江风雪"
tagline:          "Heropoo的个人博客"
description:      "时光漫漫，何妨扬眉淡笑，心境从容？"
url:              http://www.ioio.pw
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           Heropoo
  url:            http://www.ioio.pw

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed

disqus.
  - shortname:    heropoo

# Custom vars
version:            1.0
sidebar_home_link:  true
github:
  repo:             https://github.com/heropoo
