# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            "满江风雪"
tagline:          "Heropoo的个人博客"
say_something:    "时光漫漫，何妨扬眉淡笑，心境从容？"
description:      "满江风雪，Heropoo的个人博客。"
url:              https://forever.run
baseurl:          # the optional subpath of your site, e.g. "/blog"
domain:           forever.run

#timezone:         '+0800'

author:
  name:           Heropoo
  url:            https://forever.run

paginate:         15

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

sass:
  sass_dir:       _sass
  style:          compressed

# for `jekyll-seo-tag`
logo:             favicon.png
lang:             zh-CN 
keywords:         forever.run, 满江风雪, heropoo, 博客, 个人博客, Heropoo的个人博客, heropoo博客
# Comments
disqus:
  shortname:      heropoo

#youyan:
#  uid:            2143551

# Custom vars
version:            1.0
sidebar_home_link:  true
github:
  repo:             https://github.com/heropoo
