# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            "满江风雪"
tagline:          "Heropoo的个人博客"
description:      "  我还是很喜欢你，像风走了八千里，不问归期。"
url:              http://www.ioio.pw
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           Heropoo
  url:

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed

# Custom vars
version:            1.0
sidebar_home_link:  true
github:
  repo:             https://github.com/heropoo
