version: '2'
services: 
    site-init:
        image: jekyll/jekyll
        volumes:
            - ./:/srv/jekyll
            - ./vendor/bundle:/usr/local/bundle
        command: bundle update
    site:
        image: jekyll/jekyll
        volumes:
            - ./:/srv/jekyll
            - ./vendor/bundle:/usr/local/bundle
        command: jekyll serve --watch --incremental
        ports:
            - 4000:4000
    # site-serve:
    #     image: heropoo/jekyll-site
    #     depends_on:
    #         - site
    #     volumes:
    #         - ./:/srv/jekyll
    #         - ./vendor/bundle:/usr/local/bundle
    #     command: jekyll serve --watch --incremental
    #     ports:
    #         - 4000:4000
